### ISSUE TITLE
[BUG] - Integratie issue tussen vl-map-sheet en vl-tabs

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-tabs#6]
De vl tabs wrapper voor de keuze van de tabs zorgt ervoor dat er horizontal scroll komt wanneer deze in bvb vl-map-sheet gebruikt wordt. 

Dit komt doordat de vl-tabs--alt css voor een size van 500% vraagt. Volgende extra CSS zorgt voor een fix. Dus we overschrijven de width in de vl-ui-tabs component.

``` CSS
.vl-tabs--alt::before {
   width: auto;
}
```
